spring.application.name=user

server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/msjava-user?currentSchema=core
spring.datasource.username=admin
spring.datasource.password=123456
spring.jpa.hibernate.ddl-auto=update

spring.rabbitmq.addresses=amqp://admin:123456@msjava-broker:5672
